name: "servntire-network"
version: 1.0.0

client:
  organization: org1
  logging:
    level: info
    cryptoconfig:
      path: ${GOPATH}/src/github.com/chainHero/servntire/fixtures/crypto-config
    credentialStore:
     path: /tmp/servntire-store
    cryptoStore:
      path: /tmp/servntire-msp
  BCCSP:
    security:
    enabled: true
    default:
    provider: "SW"
    hashAlgorithm: "SHA2"
    softVerify: true
    level: 256
  tlsCerts:
    systemCertPool: false
  client: 
    keyfile:
    certfile:

channels:
  servntire:
    orderers: 
      -orderer.servntire.io
    peers:
      peer1.org1.servntire.io
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer2.org1.servntire.io
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    chaincode:
    
    policies:
      queryChannelConfig: 
        minResponses: 1
        maxTargets: 1
        retryOpts: 
          attemts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0


organizations:
  org1:
    mspid: org1.servntire.io
    cryptoPath: peerOrganization/org1.servntire.io/users/{userName}@org1.servntire.io/msp
    peers: 
      -peer1.org1.servntire.io
      -peer2.org1.servntire.io
    certificateAuthoroties:
      -ca.org1.servntire.io

orderers:
  orderer.servntire.io:
    url: http://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.servntire.io
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      allow-insecure: false
    tlsCACerts: 
      path: ${GOPATH}/src/github.com/chainHero/servntire/fixtures/crypto-config/ordererOrganizations/servntire.io/tlsca/tlsca.servntire.io-cert.pem

peers:
  peer1.org1.servntire.io:
    url: http://localhost:7051
    eventUrl: http://localhost:7053
    grpcOptions: ssl-target-name-override:peer1.org1.servntire.io
    keep-alive-time: 0s
    keep-alive-timeout: 20s
    keep-alive-permit: false
    allow-insecure: false
  tlsCACerts: {GOPATH}/src/github.com/chainHero/servntire/fixtures/crypto-config/peerOrganizations/org1.servntire.io/tlsca/tlsca.org1.servntire.io-cert.pem
  peer2.org1.servntire.io:
    url: http://localhost:8051
    eventUrl: http://localhost:8053
    grpcOptions: ssl-target-name-override:peer2.org1.servntire.io
    keep-alive-time: 0s
    keep-alive-timeout: 20s
    keep-alive-permit: false
    allow-insecure: false
  tlsCACerts: {GOPATH}/src/github.com/chainHero/servntire/fixtures/crypto-config/peerOrganizations/org1.servntire.io/tlsca/tlsca.org1.servntire.io-cert.pem

certificateAuthorities:
  ca.org1.servntire.io:
    url: http://localhost:7054
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
      caName: ca.org1.servntire.io
    tlsCACerts:
      path: ${GOPATH}/src/github.com/chainHero/servntire/fixtures/crypto-config/peerOrganizations/org1.servntire.io/ca/ca.servntire.io-cert.pem

entityMatchers:
  peer:
    - pattern: (\w*)peer0.org1.servntire.io(\w*)
      urlSubstitutionExp: http://localhost:7051
      eventUrlSubstitutionExp: htt://localhost:7053
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.servntire.io
      mappedHost: peer0.servntire.io

    - pattern: (\w*)peer1.org1.servntire.io(\w*)
      urlSubstitutionExp: http://localhost:8051
      eventUrlSubstitutionExp: http://localhost:8053
      sslTargetOverrideUrlSubstitutionExp: peer1.org1.servntire.io
      mappedHost: peer1.org1.servntire.io

  orderer:
    - pattern: (\w*)orderer.servntire.io(\w*)
      urlSubstitutionExp: http://localhost:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.servntire.io
      mappedHost: orderer.servntire.io

  certificateAuthorities:
    - pattern: (\w*)ca.org1.servntire.io(\w*)
      urlSubstitutionExp: http://localhost:7054
      mappedHost: ca.org1.servntire.io